quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

# Matcher service URL
matcher.api.url=http://localhost:8081
quarkus.rest-client."com.zenline.client.MatcherClient".url=${matcher.api.url}